### ISSUE TITLE
sudoers: add `/usr/libexec/ApplicationFirewall/socketfilterfw --unblock /usr/libexec/bootpd`

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1598]
It looks like lima should run `/usr/libexec/ApplicationFirewall/socketfilterfw --unblock /usr/libexec/bootpd` every time when using `socket_vmnet`
https://github.com/lima-vm/lima/issues/1259#issuecomment-1573051614

**Comment by AkihiroSuda** [comment]
The `socketfilterfw(8)` man page mentions `--unblockapp`, but does not seem to mention `--unblock`.
Maybe `--unblock` is already deprecated?

**Comment by AravindGopala** [comment]
Hi @AkihiroSuda can we bump up the priority on this, I am not so keen on how to achieve this otherwise would have submitted a PR myself. Are we planning to call the command from [commands.go](https://github.com/lima-vm/lima/blob/master/pkg/networks/commands.go) file?

**Comment by AkihiroSuda** [comment]
> Hi @AkihiroSuda can we bump up the priority on this, I am not so keen on how to achieve this otherwise would have submitted a PR myself. 

Thanks

> Are we planning to call the command from [commands.go](https://github.com/lima-vm/lima/blob/master/pkg/networks/commands.go) file?

Yes, probably

**Comment by AkihiroSuda** [comment]
Can anybody check if this is still required for macOS 14?

**Comment by AravindGopala** [comment]
@AkihiroSuda I can verify that the problem still does exist for me on macos 14.0 sonoma, without the running the unblock after every bootup of the mac I the dhcp lease does not work.

**Comment by AravindGopala** [comment]
Even worse once on sonoma macos fails to provide dhcp leases even after running the command 
`/usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /usr/libexec/bootpd`

**Comment by AkihiroSuda** [comment]
@AravindGopala Is this issue resolved with macOS 14?

**Comment by AkihiroSuda** [comment]
`socketfilterfw` seems still needed for some machines running on macOS 14: https://github.com/lima-vm/lima/issues/1259#issuecomment-1741868169

But I still can't repro the issue locally, and `sudo /usr/libexec/ApplicationFirewall/socketfilterfw  --add /usr/libexec/bootpd` fails with `"The file path you specified does not exist"` error even though `/usr/libexec/bootpd` exists.
A rumor is that `socketfilterfw` doesn't work on Japanese macOS: https://gist.github.com/techraf/ef5a6aae636f52eec09b?permalink_comment_id=2974356#gistcomment-2974356

**Comment by AravindGopala** [comment]
@AkihiroSuda sorry for the confusion, It looks like on sonoma 14.0 macos on M1 Max macbook pro, the network sharing works without issues, also colima gets the ip everytime, **_I no longer have to run the socket filter commands at boot everytime_** like before so far [Its been four days I have installed the OS, I will keep an eye, if I ever see the issue again], it looks like the issue is fixed for me.

On a side note the below commands do work for me here is USA
```
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblock /usr/libexec/bootpd
```

**Comment by AravindGopala** [comment]
Hi @AkihiroSuda, I can confirm that the issue came back for me after couple of reboots over the days, i.e the internet sharing no longer works and the VM fails to get the ip, I have manually run the command to fix it. So we need this PR.
```
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblock /usr/libexec/bootpd
```

**Comment by AkihiroSuda** [comment]
Is anyone interested in opening a PR?

I still can't use socketfilterfw by myself
