### ISSUE TITLE
Template podman/fedora is no longer able to SSH

### ISSUE THREAD

**Issue by babariviere** [lima-vm/lima#4334]
### Description

When creating a VM with podman template using lima version v2.0.1, the process is stuck in the SSH process:

```
limactl start --name=default --cpus=8 --disk=200 --memory=16 --vm-type=vz --rosetta --mount-type=virtiofs --mount-writable --network=vzNAT template:podman --progress
? Creating an instance "default" Open an editor to review or modify the current configuration
INFO[0038] Starting the instance "default" with internal VM driver "vz"
INFO[0038] Attempting to download the image              arch=aarch64 digest="sha256:66031aea9ec61e6d0d5bba12b9454e80ca94e8a79c913d37ded4c60311705b8b" location="https://dl.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/aarch64/images/Fedora-Cloud-Base-Generic-43-1.6.aarch64.qcow2"
INFO[0038] Using cache "/Users/babariviere/Library/Caches/lima/download/by-url-sha256/53f5b9386607497bb49149938c516958a3d0c8b7eae7a8b9bbba866a068788e3/data"
INFO[0039] [hostagent] hostagent socket created at /Users/babariviere/.lima/default/ha.sock
INFO[0039] [hostagent] Starting VZ (hint: to watch the boot progress, see "/Users/babariviere/.lima/default/serial*.log")
INFO[0039] [hostagent] Setting up Rosetta share
INFO[0039] [hostagent] [VZ] - vm state change: running
INFO[0046] [hostagent] Started vsock forwarder: 127.0.0.1:59344 -> vsock:22 on VM
INFO[0046] [hostagent] Detected SSH server is listening on the vsock port; changed 127.0.0.1:59344 to proxy for the vsock port
INFO[0047] SSH Local Port: 59344
INFO[0046] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0056] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0066] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0077] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0087] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
```

Looking at the debug output, we have this:

```
{"level":"debug","msg":"executing script \"ssh\"","time":"2025-11-12T11:12:13+01:00"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /usr/bin/ssh [ssh -o ControlMaster=no -o ControlPath=none -o ControlPersist=no -F /dev/null -o IdentityFile=\"/Users/babariviere/.lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o GSSAPIAuthentication=no -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=babariviere -p 59344 127.0.0.1 -- /bin/bash -c \"$(printf 'param_env=\"$(sudo cat /mnt/lima-cidata/param.env)\"; while read -r line; do [ -n \"$line\" ] \u0026\u0026 export \"$line\"; done\u003c\u003cEOF\\n${param_env}\\nEOF\\n/bin/bash')\"]","time":"2025-11-12T11:12:13+01:00"}
{"level":"debug","msg":"stdout=\"\", stderr=\"Connection closed by 127.0.0.1 port 59344\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"Connection closed by 127.0.0.1 port 59344\\r\\n\": exit status 255","time":"2025-11-12T11:12:13+01:00"}
```

Default template is working well, so I guess this is an issue with fedora cloud image 🤔 
Also replacing the image with centos-stream works well with podman.

**Comment by unsuman** [comment]
> Default template is working well, so I guess this is an issue with fedora cloud image 🤔

Yes it seems that's the case, you can use Fedora-42 as a workaround

**Comment by norio-nomura** [comment]
Fedora seems to refuse to connect to SSH over VSOCK.
Please try using `LIMA_SSH_OVER_VSOCK=false limactl start ...`

**Comment by norio-nomura** [comment]
opened #4337

**Comment by afbjorklund** [comment]
This issue seems specific to the vz driver, didn't see any issues with the qemu driver.

**Comment by AkihiroSuda** [comment]
> Fedora seems to refuse to connect to SSH over VSOCK.

What configuration is different on Fedora ?

**Comment by AkihiroSuda** [comment]
Also curious why it still works with Fedora 42 (systemd 257).
What change on Fedora 43 broke the compatibility with `LIMA_SSH_OVER_VSOCK` ?

**Comment by norio-nomura** [comment]
Fedora accepts TCP connection with VSOCK for the time being, but when it tries to communicate, it is disconnected.
In the current implementation, whether ssh connection is possible with VSOCK:22 is determined by whether or not TCP connection is accepted.
Therefore, the current implementation determines that it is possible to connect and configures forward to VSOCK, but if the SSH client actually connects, it fails.
Therefore, #4337 is trying to determine whether SSH can be connected via VSOCK by implementing the actual SSH protocol handshake.

Originally, I tried to make a judgment by exchanging data that imitated the SSH protocol, but since I was working on #4333, I implemented #4337 using x/crypto/ssh.

**Comment by AkihiroSuda** [comment]
> Fedora accepts TCP connection with VSOCK for the time being, but when it tries to communicate, it is disconnected.


I still do not understand why it is disconnected. (`ssh_dispatch_run_fatal: Connection from UNKNOWN port 65535: Permission denied [preauth]`)

Client:
```
INFO[0009] [hostagent] Started vsock forwarder: 127.0.0.1:54710 -> vsock:22 on VM 
INFO[0009] [hostagent] Detected SSH server is listening on the vsock port; changed 127.0.0.1:54710 to proxy for the vsock port 
INFO[0009] SSH Local Port: 54710
```

```console
$ telnet 127.0.0.1 54710
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
SSH-2.0-OpenSSH_10.0
^]
telnet> q
Connection closed.

$ ssh -vvvvv -i  ~/.lima/_config/user -p 54710  127.0.0.1
debug1: OpenSSH_10.0p2, LibreSSL 3.3.6
debug3: Running on Darwin 25.1.0 Darwin Kernel Version 25.1.0: Mon Oct 20 19:34:05 PDT 2025; root:xnu-12377.41.6~2/RELEASE_ARM64_T6041 arm64
debug3: Started with: ssh -vvvvv -i /Users/suda/.lima/_config/user -p 54710 127.0.0.1
debug1: Reading configuration data /Users/suda/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug3: /etc/ssh/ssh_config line 22: Including file /etc/ssh/ssh_config.d/100-macos.conf depth 0
debug1: Reading configuration data /etc/ssh/ssh_config.d/100-macos.conf
debug1: /etc/ssh/ssh_config.d/100-macos.conf line 1: Applying options for *
debug3: /etc/ssh/ssh_config.d/100-macos.conf line 3: Including file /etc/ssh/crypto.conf depth 1
debug1: Reading configuration data /etc/ssh/crypto.conf
debug3: kex names ok: [ecdh-sha2-nistp256]
debug2: resolve_canonicalize: hostname 127.0.0.1 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/suda/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/suda/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug3: channel_clear_timeouts: clearing
debug3: ssh_connect_direct: entering
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 54710.
debug3: set_sock_tos: set socket 3 IP_TOS 0x48
debug1: Connection established.
debug1: identity file /Users/suda/.lima/_config/user type 3
debug1: identity file /Users/suda/.lima/_config/user-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_10.0
debug1: Remote protocol version 2.0, remote software version OpenSSH_10.0
debug1: compat_banner: match: OpenSSH_10.0 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 127.0.0.1:54710 as 'suda'
debug3: put_host_port: [127.0.0.1]:54710
debug1: load_hostkeys: fopen /Users/suda/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug3: order_hostkeyalgs: no algorithms matched; accept original
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
Connection closed by 127.0.0.1 port 54710
```

Daemon log (fetched by SSHing to Fedora from Ubuntu in the same user-v2 network)
```console
$ sudo journalctl -f
[...]
Nov 21 03:49:47 lima-fedora systemd[1]: Starting sshd@53-8208-3:22-2:3551058913.service - OpenSSH per-connection server daemon (vsock:2:3551058913)...
Nov 21 03:49:47 lima-fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=sshd@53-8208-3:22-2:3551058913 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 21 03:49:47 lima-fedora systemd[1]: Started sshd@53-8208-3:22-2:3551058913.service - OpenSSH per-connection server daemon (vsock:2:3551058913).
Nov 21 03:49:47 lima-fedora sshd-session[1360]: ssh_dispatch_run_fatal: Connection from UNKNOWN port 65535: Permission denied [preauth]
Nov 21 03:49:47 lima-fedora audit[1360]: AUDIT1112 pid=1360 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_session_t:s0-s0:c0.c1023 msg='op=login acct="(unknown)" exe="/usr/libexec/openssh/sshd-session" hostname=? addr=UNKNOWN terminal=ssh res=failed'
Nov 21 03:49:47 lima-fedora systemd[1]: sshd@53-8208-3:22-2:3551058913.service: Deactivated successfully.
Nov 21 03:49:47 lima-fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=sshd@53-8208-3:22-2:3551058913 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

**Comment by AkihiroSuda** [comment]
This seems to be a SELinux configuration issue.
`setenforce 0` seems to work as a workaround.

```console
# ausearch -m AVC,USER_AVC -ts recent
----
time->Fri Nov 21 04:10:25 2025
type=AVC msg=audit(1763698225.743:248): avc:  denied  { getattr } for  pid=1355 comm="sshd-auth" scontext=system_u:system_r:sshd_auth_t:s0-s0:c0.c1023 tcontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tclass=vsock_socket permissive=1
```
